sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ZFh5aZ8apx0B+JFJ0cab5iCjJbf42UEPFASD+/StLh6z4Uo7ZVCdA+7aB9EhvtwDQBuDSJ642nJK3xNpiOEDHcA1R2c347O+5RjUX3hfrckFpPQekqomZK8vHIHEbmdpxVZ95+4xFea8urL30ax0SS40W3VG3qwDLHyft6kQ/mbPevLa08lin1mQ5OdTxL+Agns7vwAPOuHqd5WcFHCUtD5rtNxVf0c0DJJ5UpVaqaMsgr+Splr1tVy+2jPRJF6QApTmuR00rTirnjMqR81z8tSZJO7PIX6dVfBBt3y34LUWv3RC6Yk1r2+Ee3dss3tF4HQoHiugbSmD17jnWNux74JC45kZvVl8mM9uPC5RTiG3506HFL+KUJWwv3bdr7WBuKgihrtwgM2CvPOMBQmcnMIFtLg6B50981qOBT/d2nqXxLMikFjMkOldiPHukggSjBRSKQBh/J2nmp8NsbpPxSTECxUNFG+W7gMosSCsesYf/+LZg3owIW2YAuk24l3eZtIYgtd9QcL5SlCX+GflNL5MwSihI5rTHZOTYyLYSaSknswI+A7QTlVuIjEe2xgbyGlSZlkRo0nTM/S0LutdEaUso+it2MGLxITHv04F9eIQYCj03Qcp0wJmyyf0TG4Zm6DXOew546GW/JQGWCCmNn7nodZ8OCDNYbJEYDAY0pk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/When-a-Man-Marries_1671
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy